classDiagram
    class Game {
        <<class>>
        +bool IsActive
        -World _world
        -Player player
    }
    class Player {
        <<abstract>>
        !-int MaxHealth
        +string Name
        +int Health
        
    }
    
